[package]
license      = "MIT OR Apache-2.0"
name         = "ratatui-wgpu"
version      = "0.1.1"
edition      = "2021"
rust-version = "1.75.0"
repository   = "https://github.com/Jesterhearts/ratatui-wgpu"
description  = "A wgpu based backend for ratatui."
keywords     = [ "wasm", "tui", "rendering" ]

[features]
web = [ "wgpu/webgl" ]

[[example]]
name              = "hello_web"
path              = "examples/web/hello_web.rs"
required-features = [ "web" ]

[[example]]
name              = "hello_webworker"
path              = "examples/web/hello_webworker.rs"
required-features = [ "web" ]

[dependencies]
bytemuck      = { version = "1.17.0", features = [ "derive" ] }
coolor        = "1.0.0"
indexmap      = { version = "2.4.0", default-features = false, features = [ "std" ] }
log           = { version = "0.4.22", default-features = false }
palette       = { version = "0.7.6", default-features = false, features = [ "std", "named" ] }
ratatui       = { version = "0.28.0", default-features = false }
rustybuzz     = "0.18.0"
thiserror     = "1.0.63"
tiny-skia     = { version = "0.11.4", default-features = false, features = [ "simd", "std" ] }
unicode-width = "0.1.13"
wgpu          = "22.1.0"

[dev-dependencies]
anyhow                   = "1.0.86"
chrono                   = "0.4.38"
console_error_panic_hook = "0.1.7"
console_log              = "1.0.0"
crossbeam-queue          = "0.3.11"
env_logger               = "0.11.5"
futures-lite             = "2.3.0"
image                    = { version = "0.25.2", default-features = false, features = [ "png" ] }
js-sys                   = "0.3.70"
oneshot                  = "0.1.8"
serial_test              = "3.1.1"
wasm-bindgen             = "0.2"
wasm-bindgen-futures     = "0.4.42"
web-sys                  = { version = "0.3.70", features = [ "MessageEvent", "Worker", "WorkerOptions", "WorkerType" ] }
winit                    = "0.30.5"
